from pydantic import BaseModel
from typing import Optional


# Used for POST — creating a new user
# Client must send: name, email, age
# Client may send: city
class UserCreate(BaseModel):
    name: str
    email: str
    age: int
    city: Optional[str] = None


# Used for PUT — full replacement
# All fields required (same as Create)
class UserUpdate(BaseModel):
    name: str
    email: str
    age: int
    city: Optional[str] = None


# Used for PATCH — partial update
# All fields optional — only sent fields get updated
class UserPatch(BaseModel):
    name: Optional[str] = None
    email: Optional[str] = None
    age: Optional[int] = None
    city: Optional[str] = None


# Used for responses — what the client sees
# Includes id (auto-generated by database)
class UserResponse(BaseModel):
    id: int
    name: str
    email: str
    age: int
    city: Optional[str] = None

    # This tells Pydantic to read data from SQLAlchemy objects
    # Without this, Pydantic cannot convert a SQLAlchemy User → JSON
    class Config:
        from_attributes = True